# Generated by Django 4.2.5 on 2024-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainoeuvre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryservice",
            name="description",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="prestataire",
            name="est_disponible",
            field=models.BooleanField(default=True),
        ),
    ]
